accounts/urls.py
from django.urls import path
from accounts.views import signup, logout_user, login_user, profile, set_default_shipping_address, delete_address

app_name = 'accounts'

urlpatterns = [
    path('signup/', signup, name="signup"),
    path('delete_address/<int:pk>/', delete_address, name="delete-address"),
    path('login/', login_user, name="login"),
    path('logout/', logout_user, name="logout"),
    path('profile/', profile, name="profile"),
    path('profile/set_default_shipping/<int:pk>/', set_default_shipping_address, name="set-default-shipping"),
]

shop/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from shop import settings
from store.views import index

urlpatterns = [
      path('', index, name='index'),
      path('admin/', admin.site.urls),
      path('account/', include('accounts.urls')),
      path('boutique/', include('store.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
import stripe
from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.shortcuts import get_object_or_404
from iso3166 import countries

from shop import settings
from store.models import Product, Cart, Order

stripe.api_key = settings.STRIPE_API_KEY


class CustomUserManager(BaseUserManager):
    def create_user(self, email, password, **kwargs):
        if not email:
            raise ValueError("L'adresse email est obligatoire.")
        email = self.normalize_email(email)
        user = self.model(email=email, **kwargs)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, **kwargs):
        kwargs.setdefault("is_staff", True)
        kwargs.setdefault("is_superuser", True)
        kwargs.setdefault("is_active", True)

        if kwargs.get("is_staff") is False:
            raise ValueError("Le super utilisateur doit faire partie de l'équipe d'administration.")
        if kwargs.get("is_superuser") is False:
            raise ValueError("Le super utilisateur doit être super utilisateur.")

        return self.create_user(email=email, **kwargs)


class Shopper(AbstractUser):
    username = None
    email = models.EmailField(max_length=240, unique=True)
    stripe_id = models.CharField(max_length=90, blank=True)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []
    objects = CustomUserManager()

    def add_to_cart(self, slug):
        product = get_object_or_404(Product, slug=slug)
        cart, _ = Cart.objects.get_or_create(user=self)
        order, created = Order.objects.get_or_create(user=self,
                                                     product=product)

        if created:
            cart.orders.add(order)
            cart.save()
        else:
            order.quantity += 1
            order.save()

        return cart


ADDRESS_FORMAT = """
{name}
{address_1}
{address_2}
{city}, {zip_code}
{country}
"""


class ShippingAddress(models.Model):
    user: Shopper = models.ForeignKey(Shopper, on_delete=models.CASCADE, related_name="addresses")
    name = models.CharField(max_length=1024)
    address_1 = models.CharField(max_length=1024, help_text="Adresse de voirie et numéro de rue.")
    address_2 = models.CharField(max_length=1024, blank=True, help_text="Bâtiment, étage, lieu-dit...")
    city = models.CharField(max_length=1024)
    zip_code = models.CharField(max_length=24)
    country = models.CharField(max_length=2, choices=[(c.alpha2.lower(), c.name) for c in countries])
    default = models.BooleanField(default=False)

    def __str__(self):
        data = self.__dict__.copy()
        data.update(country=self.get_country_display().upper())
        return ADDRESS_FORMAT.format(**data).strip("\n")

    def as_dict(self):
        return {
            "city": self.city,
            "country": self.country,
            "line1": self.address_1,
            "line2": self.address_2,
            "postal_code": self.zip_code
        }

    def set_default(self):
        if not self.user.stripe_id:
            raise ValueError(f"User {self.user.email} doesn't have a stripe Customer ID.")

        self.user.addresses.update(default=False)
        self.default = True
        self.save()

        stripe.Customer.modify(
                self.user.stripe_id,
                shipping={"name": self.name,
                          "address": self.as_dict()},
                address=self.as_dict()
        )

accounts/forms.py
from django import forms

from accounts.models import Shopper


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = Shopper
        fields = ["first_name", "last_name", "email", "password"]

accounts/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model, login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404

from accounts.forms import UserForm
from accounts.models import ShippingAddress

User = get_user_model()


def signup(request):
    if request.method == "POST":
        # Traiter le formulaire
        email = request.POST.get("email")
        password = request.POST.get("password")
        user = User.objects.create_user(email=email,
                                        password=password)
        login(request, user)
        return redirect('index')

    return render(request, 'accounts/signup.html')


def login_user(request):
    if request.method == "POST":
        # Connecter l'utilisateur
        email = request.POST.get("email")
        password = request.POST.get("password")

        user = authenticate(email=email, password=password)
        if user:
            login(request, user)
            return redirect('index')

    return render(request, 'accounts/login.html')


def logout_user(request):
    logout(request)
    return redirect('index')


@login_required
def profile(request):
    if request.method == "POST":
        is_valid = authenticate(email=request.POST.get("email"),
                                password=request.POST.get("password"))
        if is_valid:
            user = request.user
            user.first_name = request.POST.get("first_name")
            user.last_name = request.POST.get("last_name")
            user.save()
        else:
            messages.add_message(request, messages.ERROR, "Le mot de passe n'est pas valide.")

        return redirect('accounts:profile')

    form = UserForm(instance=request.user)
    addresses = request.user.addresses.all()

    return render(request, 'accounts/profile.html', context={"form": form,
                                                             "addresses": addresses})


@login_required
def set_default_shipping_address(request, pk):
    address: ShippingAddress = get_object_or_404(ShippingAddress, pk=pk)
    address.set_default()
    return redirect('accounts:profile')


@login_required
def delete_address(request, pk):
    address = get_object_or_404(ShippingAddress, pk=pk, user=request.user)
    address.delete()
    return redirect('accounts:profile')

accounts/templates/accounts/address.html
<div>
    <h3>{{ address.name }} {% if address.default %} - défaut{% endif %}</h3>

    <p>
        {{ address.address_1 }}
    </p>
    {% if address.address_2 %}
        <p>
            {{ address.address_2 }}
        </p>
    {% endif %}
    <p>
        {{ address.city }}, {{ address.zip_code }}
    </p>
    <p>
        {{ address.get_country_display|upper }}
    </p>

    {% if not address.default %}
        <a href="{% url 'accounts:set-default-shipping' address.pk %}">
            Définir par défaut
        </a>
    {% endif %}

    <p>
        <a href="{% url 'accounts:delete-address' address.pk %}">Supprimer l'adresse</a>
    </p>

</div>

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}

    <h1>Connexion</h1>
    <form method="POST">
        {% csrf_token %}
        <p>
            <label for="username">Nom d'utilisateur</label>
            <input id="username" type="text" name="username">
        </p>
        <p>
            <label for="password">Mot de passe</label>
            <input id="password" type="password" name="password">
        </p>
        <button type="submit">Connexion</button>
    </form>


{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block content %}

<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}

    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    <button type="submit">Sauvegarder</button>
</form>

{% if addresses %}
    <h1>Adresses de livraison</h1>
{% endif %}

{% for address in addresses %}

{% include 'accounts/address.html' %}

{% endfor %}


{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}

    <h1>S'inscrire</h1>
    <form method="POST">
        {% csrf_token %}
        <p>
            <label for="email">Adresse mail</label>
            <input id="email" type="text" name="email">
        </p>
        <p>
            <label for="password">Mot de passe</label>
            <input id="password" type="password" name="password">
        </p>
        <button type="submit">S'inscrire</button>
    </form>


{% endblock %}