accounts/urls.py
from django.urls import path
from accounts.views import signup, logout_user, login_user, profile, set_default_shipping_address, delete_address

app_name = 'accounts'

urlpatterns = [
    path('signup/', signup, name="signup"),
    path('delete_address/<int:pk>/', delete_address, name="delete-address"),
    path('login/', login_user, name="login"),
    path('logout/', logout_user, name="logout"),
    path('profile/', profile, name="profile"),
    path('profile/set_default_shipping/<int:pk>/', set_default_shipping_address, name="set-default-shipping"),
]

shop/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from shop import settings
from store.views import index

urlpatterns = [
      path('', index, name='index'),
      path('admin/', admin.site.urls),
      path('account/', include('accounts.urls')),
      path('boutique/', include('store.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path

from store.views import index, product_detail, add_to_cart, cart, delete_cart, create_checkout_session, stripe_webhook, checkout_success, update_quantities

app_name = "store"

urlpatterns = [
    path('cart/', cart, name="cart"),
    path('cart/update_quantities/', update_quantities, name="update-quantities"),
    path('stripe-webhook/', stripe_webhook, name="stripe-webhook"),
    path('cart/create-checkout-session/', create_checkout_session, name="create-checkout-session"),
    path('cart/success/', checkout_success, name="checkout-success"),
    path('cart/delete/', delete_cart, name="delete-cart"),
    path('product/<str:slug>/', product_detail, name="product"),
    path('product/<str:slug>/add-to-cart/', add_to_cart, name="add-to-cart"),
]

templates/base.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>La boutique de Docstring</title>
</head>
<body>

<a href="{% url 'index' %}">
    <h1>La boutique de Docstring</h1>
</a>

{% if user.is_authenticated %}
    {{ user.email }}
    <a href="{% url 'accounts:profile' %}">Mon profil</a>
    <a href="{% url 'accounts:logout' %}">Déconnexion</a>
{% else %}
    <a href="{% url 'accounts:login' %}">Connexion</a>
    <a href="{% url 'accounts:signup' %}">S'inscrire</a>
{% endif %}

{% if user.cart and not user.cart.ordered %}
<p>
    <a href="{% url 'store:cart' %}">Voir le panier ({{ user.cart.orders.count }})</a>
</p>
{% endif %}


{% block content %}
{% endblock %}

</body>
</html>